spring:
  application:
    name: springboot-Junit-Mockito
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: cogent
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect